"""KeyCall: one consistent interface for validating AI-provider API keys,
listing and filtering their models, and making normalized calls."""

from ._client import AsyncKeyCall, AsyncTextStream, KeyCall, TextStream
from ._enums import ModelCategory, Operation, ProviderProtocol
from ._errors import ErrorCode, KeyCallError
from ._types import (
    AudioInput,
    AudioOutput,
    Citation,
    CitationFound,
    EmbeddingOutput,
    FileInput,
    FileOutput,
    ImageInput,
    ImageOutput,
    InputPart,
    InvocationResult,
    Message,
    MessageRole,
    Model,
    ModelDiscovery,
    OutputPart,
    StreamEvent,
    StreamFinish,
    StreamStart,
    TextDelta,
    TextGenerationRequest,
    TextInput,
    TextOutput,
    Tool,
    ToolCall,
    ToolCallArgumentsDelta,
    ToolCallComplete,
    ToolCallStarted,
    ToolResult,
    TranscriptOutput,
    UnknownOutput,
    UnknownStreamEvent,
    Usage,
    VideoOutput,
)

__version__ = "0.8.0"

__all__ = [
    "AsyncKeyCall",
    "AsyncTextStream",
    "AudioInput",
    "AudioOutput",
    "Citation",
    "CitationFound",
    "EmbeddingOutput",
    "ErrorCode",
    "FileInput",
    "FileOutput",
    "ImageInput",
    "ImageOutput",
    "InputPart",
    "InvocationResult",
    "KeyCall",
    "KeyCallError",
    "Message",
    "MessageRole",
    "Model",
    "ModelCategory",
    "ModelDiscovery",
    "Operation",
    "OutputPart",
    "ProviderProtocol",
    "StreamEvent",
    "StreamFinish",
    "StreamStart",
    "TextDelta",
    "TextGenerationRequest",
    "TextInput",
    "TextOutput",
    "TextStream",
    "Tool",
    "ToolCall",
    "ToolCallArgumentsDelta",
    "ToolCallComplete",
    "ToolCallStarted",
    "ToolResult",
    "TranscriptOutput",
    "UnknownOutput",
    "UnknownStreamEvent",
    "Usage",
    "VideoOutput",
    "__version__",
]
