"""KeyCall: one consistent interface for validating AI-provider API keys,
listing and filtering their models, and making normalized calls."""

from ._client import AsyncKeyCall, AsyncTextStream, KeyCall, TextStream
from ._enums import ModelCategory, Operation, ProviderProtocol
from ._errors import ErrorCode, KeyCallError, VideoJobTimeout
from ._realtime import AsyncRealtimeSession, RealtimeSession
from ._types import (
    AudioInput,
    AudioOutput,
    Citation,
    CitationFound,
    EmbeddingOutput,
    EmbeddingRequest,
    FileInput,
    FileOutput,
    ImageGenerationRequest,
    ImageInput,
    ImageOutput,
    InputPart,
    InvocationResult,
    Message,
    MessageRole,
    Model,
    ModelDiscovery,
    OutputPart,
    RealtimeAudioDelta,
    RealtimeConfig,
    RealtimeEvent,
    RealtimeInterrupted,
    RealtimeSessionEnded,
    RealtimeSessionStarted,
    RealtimeTranscriptDelta,
    RealtimeTurnComplete,
    ReasoningDelta,
    SpeechGenerationRequest,
    StreamEvent,
    StreamFinish,
    StreamStart,
    TextDelta,
    TextGenerationRequest,
    TextInput,
    TextOutput,
    Tool,
    ToolCall,
    ToolCallArgumentsDelta,
    ToolCallComplete,
    ToolCallStarted,
    ToolResult,
    TranscriptOutput,
    UnknownOutput,
    UnknownRealtimeEvent,
    UnknownStreamEvent,
    Usage,
    VideoGenerationRequest,
    VideoJob,
    VideoJobStatus,
    VideoOutput,
)

__version__ = "1.0.0"

__all__ = [
    "AsyncKeyCall",
    "AsyncRealtimeSession",
    "AsyncTextStream",
    "AudioInput",
    "AudioOutput",
    "Citation",
    "CitationFound",
    "EmbeddingOutput",
    "EmbeddingRequest",
    "ErrorCode",
    "FileInput",
    "FileOutput",
    "ImageGenerationRequest",
    "ImageInput",
    "ImageOutput",
    "InputPart",
    "InvocationResult",
    "KeyCall",
    "KeyCallError",
    "Message",
    "MessageRole",
    "Model",
    "ModelCategory",
    "ModelDiscovery",
    "Operation",
    "OutputPart",
    "ProviderProtocol",
    "RealtimeAudioDelta",
    "RealtimeConfig",
    "RealtimeEvent",
    "RealtimeInterrupted",
    "RealtimeSession",
    "RealtimeSessionEnded",
    "RealtimeSessionStarted",
    "RealtimeTranscriptDelta",
    "RealtimeTurnComplete",
    "ReasoningDelta",
    "SpeechGenerationRequest",
    "StreamEvent",
    "StreamFinish",
    "StreamStart",
    "TextDelta",
    "TextGenerationRequest",
    "TextInput",
    "TextOutput",
    "TextStream",
    "Tool",
    "ToolCall",
    "ToolCallArgumentsDelta",
    "ToolCallComplete",
    "ToolCallStarted",
    "ToolResult",
    "TranscriptOutput",
    "UnknownOutput",
    "UnknownRealtimeEvent",
    "UnknownStreamEvent",
    "Usage",
    "VideoGenerationRequest",
    "VideoJob",
    "VideoJobStatus",
    "VideoJobTimeout",
    "VideoOutput",
    "__version__",
]
